ffb:
  availableConnections:
    - name: conn1
      apiBaseUrl: http://localhost:22228
      jnlpUrl: http://localhost:22228/jnlp1
    - name: conn2
      apiBaseUrl: http://localhost:22228
      jnlpUrl: http://localhost:22228/jnlp2
  primaryName: conn2